---
title: "Diabetes"
output: html_document
date: "2025-10-22"
---

```{r include=FALSE}
#install.packages("dplyr")
library(dplyr)
```

```{r}
diabetes = read.csv("diabetes.csv", head=TRUE, sep=",")
summary(diabetes)
```

```{r}
diabetes <- diabetes %>%
  mutate(
    Glucose = na_if(Glucose, 0),
    BloodPressure = na_if(BloodPressure, 0),
    SkinThickness = na_if(SkinThickness, 0),
    BMI = na_if(BMI, 0),
    DiabetesPedigreeFunction = na_if(DiabetesPedigreeFunction, 0),
  )
summary(diabetes)
```


```{r}
diabetes <- diabetes %>%
  mutate(
    Glucose = if_else(is.na(Glucose), median(Glucose, na.rm = TRUE), Glucose),
    BloodPressure = if_else(is.na(BloodPressure), median(BloodPressure, na.rm = TRUE), BloodPressure),
    SkinThickness = if_else(is.na(SkinThickness), median(SkinThickness, na.rm = TRUE), SkinThickness),
    BMI = if_else(is.na(BMI), median(BMI, na.rm = TRUE), BMI),
    DiabetesPedigreeFunction = if_else(is.na(DiabetesPedigreeFunction), median(DiabetesPedigreeFunction, na.rm = TRUE), DiabetesPedigreeFunction)
  )

summary(diabetes)
```

